### ISSUE TITLE
ssdeep 2.14 support

### ISSUE THREAD

**Issue by davidt99** [DinoTools/python-ssdeep#33]
ssdeep just released 2.14, there is any plan to update the included lib?

**Comment by phibos** [comment]
I have update the shipped ssdeep lib from 2.13 to 2.14.1 and all builds and tests run successful.

**Comment by davidt99** [comment]
Cool thanks!

**Comment by phibos** [comment]
There is also a new release in the PyPI https://pypi.python.org/pypi/ssdeep/3.3
