### ISSUE TITLE
Missing docs at pypi

### ISSUE THREAD

**Issue by wagner-certat** [DinoTools/python-ssdeep#37]
The [file at pypi](https://pypi.org/project/ssdeep/#files) does not include the LICENSE, docs/ and tests/files/ files. However, building the sdist file of the package locally, does include those files.

Is there a reason for these differences?

**Comment by phibos** [comment]
Version 3.4 has been released and all required files should be included in the archive.

**Comment by phibos** [comment]
Looks like this issues has been fixed 1 year ago.

Thanks for reporting the problem. I'm closing the issue.
