### ISSUE TITLE
ssdeep failing to find homologues in BYTE data

### ISSUE THREAD

**Issue by garyhski1** [DinoTools/python-ssdeep#53]
##### ISSUE TYPE
- Bug Report

##### Python ssdeep VERSION
```
ssdeep                       3.4
```

##### OS / ENVIRONMENT
**OS**:
- Ubuntu 16.04

**Python version**:
- Python 3.6

**ssdeep lib**:

##### SUMMARY

Attempting to compare two small BYTE strings which differ by a single BYTE.  ssdeep.compare reports a comparison of 0.

##### STEPS TO REPRODUCE
b1 = b"'\xbd\xff\xd8\xaf\xbf\x00$\xaf\xb0\x00 <\x02D\x93"
b2 = b"'\xbd\xff\xd8\xaf\xbf\x00$\xaf\xb0\x00 <\x02Dk"
_h = ssdeep.Hash()
_h.update(b1)
_r1 = _h.digest()
_h.update(b2)
_r2 = _h.digest()
ssdeep.compare(_r1,_r2)
0

##### EXPECTED RESULTS
Seeing as how the inputs differ by only a single BYTE, Expected return value from ssdeep.compare() should be non-zero

##### ACTUAL RESULTS

-->
```
ssdeep.compare(_r1,_r2)
0
```

**Comment by garyhski1** [comment]
This also can be reproduced with ASCII data as follows:

import ssdeep
h1 = ssdeep.hash("1234567890")
h2 = ssdeep.hash("1234557890")
ssdeep.compare(h1,h2)
0

**Comment by garyhski1** [comment]
Conversely the following C code, which uses the libfuzzy directly - works as expected. The same data run through the PYTHON ssdeep module does not produce the expected results

#include <stdio.h>
#include <stdlib.h>
#include <fuzzy.h>

int main(int argc, char **argv)
{
    // A Piece of Binary 
    const char *a = "'\xbd\xff\xd8\xaf\xbf\x00$\xaf\xb0\x00 <\x02Dk\xaf\xa4\x00(\x8cD\x88H\x0c\x01U\xec<\x10@\x05\x8f\xa3\x00(&\x05\x1ch$\x04\x00\n\x0c\x01\xd4\xb1\xacb\x05\xfc&\x05\x1ch$\x04\x00\x0b\x0c\x01\xd4\xb1\xaf\xa2\x00\x18<\x04G{\xaf\xa2\x00\x1c\x0c\x01SH$\x843\xac\x8f\xa3\x00(<\x06Dk$\xc6\x8d$$\x04\x01\x90\x14@\x003$e\x01\xa0'\xa6\x00\x14$d\x00\x11\x0c\x01Cg'\xa5\x00\x10\x8f\xa7\x00(<\x05Dk$\xa6\x8d\\$\xe4\x00\x10\x10@\x00\x1c$\xe5\x01\xa0\r\x19\xe0\xf8$\x05\x00:\x8f\xa4\x00\x10\x0c\xd6k2$P\x00\x01\x8f\xa6\x00\x14\x10@\x00\x08\x02\x00 !\x8f\xab\x00\x10<\r\x1f\xff5\xac\xff\xff\x01lH$<\n\x80\x00\x01*@%\xaf\xa8\x00\x10\x0c\x01D\xa1\x8f\xa5\x00\x10\x0c\x01F%$\x04\x00\x02\x8f\xae\x00(<\x0fF\r%\xe6H\xd0$\x04\x01\x90\r\x19\xd9\xbc%\xc5\x01\xa0\x08\x01G\xd0\x8f\xa5\x00\x1c\r\x19\xd9\xbc$\x04\x01\x90<\x06F\x89\x8f\xb9\x00(\x8c\xd8\xc1H<\x1fDk'\xe4\x8d`\x13\x00\x00\x0e'%\x00\x10\x0c\x01Bc\x00\x00\x00\x00\x08\x01G\xd0\x8f\xa5\x00\x1c\r\x19\xd9\xbc\x00\x00\x00\x00<\x03F\x89\x8cb\xc1H<\x04Dk\x10@\x00\x03$\x84\x8dP\x0c\x01Bc\x00\x00\x00\x00\x8f\xa5\x00\x1c\x0c\x01\xd4\xb1$\x04\x00\x0b\x8f\xa5\x00\x18\x0c\x01\xd4\xb1$\x04\x00\n\x8f\xa7\x00(\x0c\x01\\B\x8c\xe4\x05\xfc\x8f\xbf\x00$\x8f\xb0\x00 \x03\xe0\x00\x08";

     // A Second piece of binary ( related to a above)
    const char *b = "'\xbd\xff\xd8\xaf\xbf\x00$\xaf\xb0\x00 <\x02D\x93\xaf\xa4\x00(\x8cD\x88H\x0c\x01V$<\x10@\x05\x8f\xa3\x00(&\x05\x1dH$\x04\x00\n\x0c\x01\xd4\xff\xacb\x05\xfc&\x05\x1dH$\x04\x00\x0b\x0c\x01\xd4\xff\xaf\xa2\x00\x18<\x04G\xb2\xaf\xa2\x00\x1c\x0c\x01S\x80$\x84\x8cl\x8f\xa3\x00(<\x06D\x93$\xc6\x8d$$\x04\x01\x90\x14@\x003$e\x01\xa0'\xa6\x00\x14$d\x00\x11\x0c\x01C\x9f'\xa5\x00\x10\x8f\xa7\x00(<\x05D\x93$\xa6\x8d\\$\xe4\x00\x10\x10@\x00\x1c$\xe5\x01\xa0\r#\xb4<$\x05\x00:\x8f\xa4\x00\x10\x0c\xdf\xd7\xc4$P\x00\x01\x8f\xa6\x00\x14\x10@\x00\x08\x02\x00 !\x8f\xab\x00\x10<\r\x1f\xff5\xac\xff\xff\x01lH$<\n\x80\x00\x01*@%\xaf\xa8\x00\x10\x0c\x01D\xd9\x8f\xa5\x00\x10\x0c\x01F]$\x04\x00\x02\x8f\xae\x00(<\x0fF=%\xe6M $\x04\x01\x90\r#\xac\xcd%\xc5\x01\xa0\x08\x01H\x08\x8f\xa5\x00\x1c\r#\xac\xcd$\x04\x01\x90<\x06F\xbc\x8f\xb9\x00(\x8c\xd83\x08<\x1fD\x93'\xe4\x8d`\x13\x00\x00\x0e'%\x00\x10\x0c\x01B\x9b\x00\x00\x00\x00\x08\x01H\x08\x8f\xa5\x00\x1c\r#\xac\xcd\x00\x00\x00\x00<\x03F\xbc\x8cb3\x08<\x04D\x93\x10@\x00\x03$\x84\x8dP\x0c\x01B\x9b\x00\x00\x00\x00\x8f\xa5\x00\x1c\x0c\x01\xd4\xff$\x04\x00\x0b\x8f\xa5\x00\x18\x0c\x01\xd4\xff$\x04\x00\n\x8f\xa7\x00(\x0c\x01\\z\x8c\xe4\x05\xfc\x8f\xbf\x00$\x8f\xb0\x00 \x03\xe0\x00\x08";

    // Identical to a 
    const char *c = "'\xbd\xff\xd8\xaf\xbf\x00$\xaf\xb0\x00 <\x02Dk\xaf\xa4\x00(\x8cD\x88H\x0c\x01U\xec<\x10@\x05\x8f\xa3\x00(&\x05\x1ch$\x04\x00\n\x0c\x01\xd4\xb1\xacb\x05\xfc&\x05\x1ch$\x04\x00\x0b\x0c\x01\xd4\xb1\xaf\xa2\x00\x18<\x04G{\xaf\xa2\x00\x1c\x0c\x01SH$\x843\xac\x8f\xa3\x00(<\x06Dk$\xc6\x8d$$\x04\x01\x90\x14@\x003$e\x01\xa0'\xa6\x00\x14$d\x00\x11\x0c\x01Cg'\xa5\x00\x10\x8f\xa7\x00(<\x05Dk$\xa6\x8d\\$\xe4\x00\x10\x10@\x00\x1c$\xe5\x01\xa0\r\x19\xe0\xf8$\x05\x00:\x8f\xa4\x00\x10\x0c\xd6k2$P\x00\x01\x8f\xa6\x00\x14\x10@\x00\x08\x02\x00 !\x8f\xab\x00\x10<\r\x1f\xff5\xac\xff\xff\x01lH$<\n\x80\x00\x01*@%\xaf\xa8\x00\x10\x0c\x01D\xa1\x8f\xa5\x00\x10\x0c\x01F%$\x04\x00\x02\x8f\xae\x00(<\x0fF\r%\xe6H\xd0$\x04\x01\x90\r\x19\xd9\xbc%\xc5\x01\xa0\x08\x01G\xd0\x8f\xa5\x00\x1c\r\x19\xd9\xbc$\x04\x01\x90<\x06F\x89\x8f\xb9\x00(\x8c\xd8\xc1H<\x1fDk'\xe4\x8d`\x13\x00\x00\x0e'%\x00\x10\x0c\x01Bc\x00\x00\x00\x00\x08\x01G\xd0\x8f\xa5\x00\x1c\r\x19\xd9\xbc\x00\x00\x00\x00<\x03F\x89\x8cb\xc1H<\x04Dk\x10@\x00\x03$\x84\x8dP\x0c\x01Bc\x00\x00\x00\x00\x8f\xa5\x00\x1c\x0c\x01\xd4\xb1$\x04\x00\x0b\x8f\xa5\x00\x18\x0c\x01\xd4\xb1$\x04\x00\n\x8f\xa7\x00(\x0c\x01\\B\x8c\xe4\x05\xfc\x8f\xbf\x00$\x8f\xb0\x00 \x03\xe0\x00\x08";

	// An unrelated piece of binary
	const char *d = "'\xbd\xff\xe0\xaf\xb1\x00\x14\xaf\xbf\x00\x1c\xaf\xb2\x00\x18\x0c\xd7\x01f\xaf\xb0\x00\x10\x00@\x88!\x14@\x00\x04$\x04\x06\x10<\x04D\x99\x08\x0e\x07U$\x84\xc6\x90\r\x19\xdb0<\x12G6\x00@\x80!\x02 (!\x14@\x00\t\x00@ !<\x02G\x17\x8cD*\xdc\x8f\xbf\x00\x1c\x8f\xb2\x00\x18\x8f\xb1\x00\x14\x8f\xb0\x00\x10\x08g~<'\xbd\x00 <\x0c@8<\n@8<\x08@8%\x8b\x19\x1c%I\x19\xac%\x07\x19\xcc\xacK\x00\x00\xacI\x00\x04\xacG\x00\x08\x8eF\xc6\x94\x0c\x01FV\xac\xc2\x0f|$\x05\x00\x05\xae\x05\x06\x0c\x0cg\xdf\x18\x8eD\xc6\x94\x02\x00 !\x0c\x01E.$\x05\x00\x01\x0cg\xdf4\x8eD\xc6\x94\x8eC\xc6\x94\x02\x00 !\x8f\xbf\x00\x1c\x8f\xb2\x00\x18\x8f\xb1\x00\x14\x8f\xb0\x00\x10\xac`\x0f|\t\x19\xdb!";

    char *ahash, *bhash, *chash, *dhash;

    ahash = (char*)malloc(FUZZY_MAX_RESULT);
    bhash = (char*)malloc(FUZZY_MAX_RESULT);
    chash = (char*)malloc(FUZZY_MAX_RESULT);
    dhash = (char*)malloc(FUZZY_MAX_RESULT);

    fuzzy_hash_buf((const unsigned char *)a, FUZZY_MAX_RESULT, ahash);
    fuzzy_hash_buf((const unsigned char *)b, FUZZY_MAX_RESULT, bhash);
    fuzzy_hash_buf((const unsigned char *)c, FUZZY_MAX_RESULT, chash);
    fuzzy_hash_buf((const unsigned char *)d, FUZZY_MAX_RESULT, dhash);

    int i = fuzzy_compare(ahash,bhash);
    printf("a to b::  RESULT = %d\n",i);
    i = fuzzy_compare(ahash,chash);
    printf("a to a::  RESULT = %d\n",i);
    i = fuzzy_compare(ahash,dhash);
    printf("a to d::  RESULT = %d\n",i);

    free(ahash);
    free(bhash);
    free(chash);
    free(dhash);

}

**Comment by phibos** [comment]
The ssdeep algorithm requires at least 4kb to produce a meaningful result. See: glaslos/ssdeep#17

Should we check and raise an exception? This would change the current behaviour.
