### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by komomon** [DinoTools/python-ssdeep#54]
![image](https://user-images.githubusercontent.com/52700174/107868486-a3274200-6ebf-11eb-8dda-61369bd49085.png)
我尝试用pip3安装，但是报错，我也安装了dev setuptools等等，但是依然不行，我查找了好多方法，但是都不管用，希望您能帮忙解决，因为我很着急，谢谢。
我的windows和Ubuntu16 都不行

**Comment by phibos** [comment]
The output only shows that it has been failed, but not why. Please provide more information.

**Comment by phibos** [comment]
Feedback missing. Closing the issue.
